### ISSUE TITLE
Server crashing in vscode

### ISSUE THREAD

**Issue by iainlane** [grafana/jsonnet-language-server#103]
I got a popup from vscode saying the language server had crashed 5 times in the last 3 minutes (or something like that). I looked at the output and here it is:

```
time="2023-06-01T18:19:15+01:00" level=error msg="Hover: error parsing the document"
time="2023-06-01T18:19:16+01:00" level=error msg="DocumentSymbol: error parsing the document"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x83eabb]

goroutine 6941 [running]:
github.com/grafana/jsonnet-language-server/pkg/server.typeToString({0x0?, 0x0?})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:205 +0x27b
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItem({_, _}, {_, _}, _, {_, _})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:180 +0x125
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItemsFromRanges({0xc01c98d900, 0x1, 0x2?}, {0xc001d18c20, 0x8}, {0xc001d18c09, 0x20})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:151 +0x359
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).completionFromStack(0xc0000f62c0?, {0xc001d18c09, 0x20}, 0xc05e27d650, 0x874180?)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:93 +0x1f8
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).Completion(0xc0000f62c0, {0xce?, 0xd0?}, 0xc00bbc8b90)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:46 +0x21b
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.serverDispatch({0xa53078, 0xc000396b40}, {0xa5bd90, 0xc0000f62c0}, 0xc05e27d5f0, {0xa531c8, 0xc000396b00})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/tsserver.go:382 +0x1bd1
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.ServerHandler.func1({0xa53078, 0xc000396b40}, 0xc05e27d5f0, {0xa531c8, 0xc000396b00})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/protocol.go:154 +0x90
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.MustReplyHandler.func1({0xa53078, 0xc000396b40}, 0xc0002ac618, {0xa531c8?, 0xc000396b00?})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:35 +0xf6
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:103 +0xa3
created by github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:100 +0x20a
[Info  - 18:19:19] Connection to server got closed. Server will restart.
time="2023-06-01T18:19:19+01:00" level=info msg="Starting the language server"
time="2023-06-01T18:19:19+01:00" level=info msg="Initializing jsonnet-language-server version 0.12.0"
time="2023-06-01T18:19:19+01:00" level=info msg="Reading stdlib"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x83eabb]

goroutine 12 [running]:
github.com/grafana/jsonnet-language-server/pkg/server.typeToString({0x0?, 0x0?})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:205 +0x27b
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItem({_, _}, {_, _}, _, {_, _})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:180 +0x125
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItemsFromRanges({0xc0005ba500, 0x1, 0x2?}, {0xc000e1e120, 0x8}, {0xc000e1e109, 0x22})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:151 +0x359
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).completionFromStack(0xc0001a62c0?, {0xc000e1e109, 0x22}, 0xc000daf950, 0x874180?)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:93 +0x1f8
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).Completion(0xc0001a62c0, {0xb7?, 0xc0?}, 0xc0002820f0)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:46 +0x21b
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.serverDispatch({0xa53078, 0xc00009ae40}, {0xa5bd90, 0xc0001a62c0}, 0xc000daf620, {0xa531c8, 0xc00009ae00})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/tsserver.go:382 +0x1bd1
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.ServerHandler.func1({0xa53078, 0xc00009ae40}, 0xc000daf620, {0xa531c8, 0xc00009ae00})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/protocol.go:154 +0x90
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.MustReplyHandler.func1({0xa53078, 0xc00009ae40}, 0xc0007c4de0, {0xa531c8?, 0xc00009ae00?})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:35 +0xf6
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:103 +0xa3
created by github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:100 +0x20a
[Info  - 18:19:19] Connection to server got closed. Server will restart.
time="2023-06-01T18:19:19+01:00" level=info msg="Starting the language server"
time="2023-06-01T18:19:19+01:00" level=info msg="Initializing jsonnet-language-server version 0.12.0"
time="2023-06-01T18:19:19+01:00" level=info msg="Reading stdlib"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x83eabb]

goroutine 13 [running]:
github.com/grafana/jsonnet-language-server/pkg/server.typeToString({0x0?, 0x0?})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:205 +0x27b
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItem({_, _}, {_, _}, _, {_, _})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:180 +0x125
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItemsFromRanges({0xc000194460, 0x1, 0x2?}, {0xc0005b6ee0, 0x8}, {0xc0005b6ec9, 0x23})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:151 +0x359
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).completionFromStack(0xc0000f62c0?, {0xc0005b6ec9, 0x23}, 0xc0002a2330, 0x874180?)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:93 +0x1f8
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).Completion(0xc0000f62c0, {0xb7?, 0xc0?}, 0xc0000140f0)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:46 +0x21b
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.serverDispatch({0xa53078, 0xc000438840}, {0xa5bd90, 0xc0000f62c0}, 0xc0002a2000, {0xa531c8, 0xc000438800})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/tsserver.go:382 +0x1bd1
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.ServerHandler.func1({0xa53078, 0xc000438840}, 0xc0002a2000, {0xa531c8, 0xc000438800})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/protocol.go:154 +0x90
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.MustReplyHandler.func1({0xa53078, 0xc000438840}, 0xc00012d350, {0xa531c8?, 0xc000438800?})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:35 +0xf6
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:103 +0xa3
created by github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:100 +0x20a
[Info  - 18:19:19] Connection to server got closed. Server will restart.
time="2023-06-01T18:19:19+01:00" level=info msg="Starting the language server"
time="2023-06-01T18:19:19+01:00" level=info msg="Initializing jsonnet-language-server version 0.12.0"
time="2023-06-01T18:19:19+01:00" level=info msg="Reading stdlib"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x83eabb]

goroutine 65 [running]:
github.com/grafana/jsonnet-language-server/pkg/server.typeToString({0x0?, 0x0?})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:205 +0x27b
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItem({_, _}, {_, _}, _, {_, _})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:180 +0x125
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItemsFromRanges({0xc00021fcc0, 0x1, 0x2?}, {0xc00073c120, 0x8}, {0xc00073c109, 0x23})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:151 +0x359
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).completionFromStack(0xc0001a62c0?, {0xc00073c109, 0x23}, 0xc00025e390, 0x874180?)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:93 +0x1f8
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).Completion(0xc0001a62c0, {0xb7?, 0xc0?}, 0xc000014960)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:46 +0x21b
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.serverDispatch({0xa53078, 0xc000809b80}, {0xa5bd90, 0xc0001a62c0}, 0xc00025e060, {0xa531c8, 0xc000809b40})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/tsserver.go:382 +0x1bd1
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.ServerHandler.func1({0xa53078, 0xc000809b80}, 0xc00025e060, {0xa531c8, 0xc000809b40})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/protocol.go:154 +0x90
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.MustReplyHandler.func1({0xa53078, 0xc000809b80}, 0xc000502cd8, {0xa531c8?, 0xc000809b40?})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:35 +0xf6
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:103 +0xa3
created by github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:100 +0x20a
[Info  - 18:19:19] Connection to server got closed. Server will restart.
time="2023-06-01T18:19:19+01:00" level=info msg="Starting the language server"
time="2023-06-01T18:19:19+01:00" level=info msg="Initializing jsonnet-language-server version 0.12.0"
time="2023-06-01T18:19:19+01:00" level=info msg="Reading stdlib"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x83eabb]

goroutine 65 [running]:
github.com/grafana/jsonnet-language-server/pkg/server.typeToString({0x0?, 0x0?})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:205 +0x27b
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItem({_, _}, {_, _}, _, {_, _})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:180 +0x125
github.com/grafana/jsonnet-language-server/pkg/server.createCompletionItemsFromRanges({0xc0001c4460, 0x1, 0x2?}, {0xc0007bcee0, 0x8}, {0xc0007bcec9, 0x24})
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:151 +0x359
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).completionFromStack(0xc0001a62c0?, {0xc0007bcec9, 0x24}, 0xc0007f0360, 0x874180?)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:93 +0x1f8
github.com/grafana/jsonnet-language-server/pkg/server.(*Server).Completion(0xc0001a62c0, {0xb7?, 0xc0?}, 0xc0002780a0)
	/home/runner/work/jsonnet-language-server/jsonnet-language-server/pkg/server/completion.go:46 +0x21b
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.serverDispatch({0xa53078, 0xc0004ba5c0}, {0xa5bd90, 0xc0001a62c0}, 0xc0007f0030, {0xa531c8, 0xc0004ba580})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/tsserver.go:382 +0x1bd1
github.com/jdbaldry/go-language-server-protocol/lsp/protocol.ServerHandler.func1({0xa53078, 0xc0004ba5c0}, 0xc0007f0030, {0xa531c8, 0xc0004ba580})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/lsp/protocol/protocol.go:154 +0x90
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.MustReplyHandler.func1({0xa53078, 0xc0004ba5c0}, 0xc00012e750, {0xa531c8?, 0xc0004ba580?})
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:35 +0xf6
github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1.2()
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:103 +0xa3
created by github.com/jdbaldry/go-language-server-protocol/jsonrpc2.AsyncHandler.func1
	/home/runner/go/pkg/mod/github.com/jdbaldry/go-language-server-protocol@v0.0.0-20211013214444-3022da0884b2/jsonrpc2/handler.go:100 +0x20a
[Error - 18:19:19] The Jsonnet Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by iainlane** [comment]
Thanks. There's supposed to be an auto-update mechanism and it doesn't work for me. I needed to manually update to get the new version.
