### ISSUE TITLE
Repeated "Request textDocument/documentSymbol failed" notifications

### ISSUE THREAD

**Issue by agirardeau** [grafana/jsonnet-language-server#166]
I'm using the jsonnet vscode extension and have recently started getting persistent notifications about failed language server calls. Here's the stack trace:

```
[Error - 11:12:42 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at Hd.validate (file:///home/andrew/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:108:33594)
	at new Hd (file:///home/andrew/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
	at asDocumentSymbol (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:604:22)
	at asDocumentSymbol (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at asDocumentSymbol (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at asDocumentSymbol (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:609:31)
	at convertBatch (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/utils/async.js:193:25)
	at Object.map (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/utils/async.js:202:17)
	at Object.asDocumentSymbols (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:601:22)
	at _provideDocumentSymbols (/home/andrew/.vscode-server/extensions/grafana.vscode-jsonnet-0.7.2/node_modules/vscode-languageclient/lib/common/documentSymbol.js:83:76)
	at async MC.provideDocumentSymbols (file:///home/andrew/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)
```

Honestly if there was a way to to just silence error notifications that would be fine, but the only options for loglevel in settings are debug/info/warn/error. When I set it to error they still pop up, I would love to just silence those too. Even putting the extension in Do Not Disturb mode doesn't silence them.

**Comment by anguslees** [comment]
I still see this issue with jsonnet-lsp 0.15.0 (via grafana.vscode-jsonnet vscode extension 0.7.2).
